const COUNTRY_CODE_LIST = [
  {
    code: 'AF',
    emoji: '🇦🇫',
    name: 'Afghanistan',
    phone: '93',
    sub: 'AF-93',
  },
  {
    code: 'AX',
    emoji: '🇦🇽',
    name: 'Åland Islands',
    phone: '358',
    sub: 'AX-358',
  },
  {
    code: 'AL',
    emoji: '🇦🇱',
    name: 'Albania',
    phone: '355',
    sub: 'AL-355',
  },
  {
    code: 'DZ',
    emoji: '🇩🇿',
    name: 'Algeria',
    phone: '213',
    sub: 'DZ-213',
  },
  {
    code: 'AS',
    emoji: '🇦🇸',
    name: 'American Samoa',
    phone: '1684',
    sub: 'AS-1684',
  },
  {
    code: 'AD',
    emoji: '🇦🇩',
    name: 'Andorra',
    phone: '376',
    sub: 'AD-376',
  },
  {
    code: 'AO',
    emoji: '🇦🇴',
    name: 'Angola',
    phone: '244',
    sub: 'AO-244',
  },
  {
    code: 'AI',
    emoji: '🇦🇮',
    name: 'Anguilla',
    phone: '1264',
    sub: 'AI-1264',
  },
  {
    code: 'AQ',
    emoji: '🇦🇶',
    name: 'Antarctica',
    phone: '672',
    sub: 'AQ-672',
  },
  {
    code: 'AG',
    emoji: '🇦🇬',
    name: 'Antigua and Barbuda',
    phone: '1268',
    sub: 'AG-1268',
  },
  {
    code: 'AR',
    emoji: '🇦🇷',
    name: 'Argentina',
    phone: '54',
    sub: 'AR-54',
  },
  {
    code: 'AM',
    emoji: '🇦🇲',
    name: 'Armenia',
    phone: '374',
    sub: 'AM-374',
  },
  {
    code: 'AW',
    emoji: '🇦🇼',
    name: 'Aruba',
    phone: '297',
    sub: 'AW-297',
  },
  {
    code: 'AU',
    emoji: '🇦🇺',
    name: 'Australia',
    phone: '61',
    sub: 'AU-61',
  },
  {
    code: 'AT',
    emoji: '🇦🇹',
    name: 'Austria',
    phone: '43',
    sub: 'AT-43',
  },
  {
    code: 'AZ',
    emoji: '🇦🇿',
    name: 'Azerbaijan',
    phone: '994',
    sub: 'AZ-994',
  },
  {
    code: 'BS',
    emoji: '🇧🇸',
    name: 'Bahamas',
    phone: '1242',
    sub: 'BS-1242',
  },
  {
    code: 'BH',
    emoji: '🇧🇭',
    name: 'Bahrain',
    phone: '973',
    sub: 'BH-973',
  },
  {
    code: 'BD',
    emoji: '🇧🇩',
    name: 'Bangladesh',
    phone: '880',
    sub: 'BD-880',
  },
  {
    code: 'BB',
    emoji: '🇧🇧',
    name: 'Barbados',
    phone: '1246',
    sub: 'BB-1246',
  },
  {
    code: 'BY',
    emoji: '🇧🇾',
    name: 'Belarus',
    phone: '375',
    sub: 'BY-375',
  },
  {
    code: 'BE',
    emoji: '🇧🇪',
    name: 'Belgium',
    phone: '32',
    sub: 'BE-32',
  },
  {
    code: 'BZ',
    emoji: '🇧🇿',
    name: 'Belize',
    phone: '501',
    sub: 'BZ-501',
  },
  {
    code: 'BJ',
    emoji: '🇧🇯',
    name: 'Benin',
    phone: '229',
    sub: 'BJ-229',
  },
  {
    code: 'BM',
    emoji: '🇧🇲',
    name: 'Bermuda',
    phone: '1441',
    sub: 'BM-1441',
  },
  {
    code: 'BT',
    emoji: '🇧🇹',
    name: 'Bhutan',
    phone: '975',
    sub: 'BT-975',
  },
  {
    code: 'BO',
    emoji: '🇧🇴',
    name: 'Bolivia, Plurinational State of bolivia',
    phone: '591',
    sub: 'BO-591',
  },
  {
    code: 'BA',
    emoji: '🇧🇦',
    name: 'Bosnia and Herzegovina',
    phone: '387',
    sub: 'BA-387',
  },
  {
    code: 'BW',
    emoji: '🇧🇼',
    name: 'Botswana',
    phone: '267',
    sub: 'BW-267',
  },
  {
    code: 'BV',
    emoji: '🇧🇻',
    name: 'Bouvet Island',
    phone: '47',
    sub: 'BV-47',
  },
  {
    code: 'BR',
    emoji: '🇧🇷',
    name: 'Brazil',
    phone: '55',
    sub: 'BR-55',
  },
  {
    code: 'IO',
    emoji: '🇮🇴',
    name: 'British Indian Ocean Territory',
    phone: '246',
    sub: 'IO-246',
  },
  {
    code: 'BN',
    emoji: '🇧🇳',
    name: 'Brunei Darussalam',
    phone: '673',
    sub: 'BN-673',
  },
  {
    code: 'BG',
    emoji: '🇧🇬',
    name: 'Bulgaria',
    phone: '359',
    sub: 'BG-359',
  },
  {
    code: 'BF',
    emoji: '🇧🇫',
    name: 'Burkina Faso',
    phone: '226',
    sub: 'BF-226',
  },
  {
    code: 'BI',
    emoji: '🇧🇮',
    name: 'Burundi',
    phone: '257',
    sub: 'BI-257',
  },
  {
    code: 'KH',
    emoji: '🇰🇭',
    name: 'Cambodia',
    phone: '855',
    sub: 'KH-855',
  },
  {
    code: 'CM',
    emoji: '🇨🇲',
    name: 'Cameroon',
    phone: '237',
    sub: 'CM-237',
  },
  {
    code: 'CV',
    emoji: '🇨🇻',
    name: 'Cape Verde',
    phone: '238',
    sub: 'CV-238',
  },
  {
    code: 'KY',
    emoji: '🇰🇾',
    name: 'Cayman Islands',
    phone: '345',
    sub: 'KY-345',
  },
  {
    code: 'CF',
    emoji: '🇨🇫',
    name: 'Central African Republic',
    phone: '236',
    sub: 'CF-236',
  },
  {
    code: 'TD',
    emoji: '🇹🇩',
    name: 'Chad',
    phone: '235',
    sub: 'TD-235',
  },
  {
    code: 'CL',
    emoji: '🇨🇱',
    name: 'Chile',
    phone: '56',
    sub: 'CL-56',
  },
  {
    code: 'CN',
    emoji: '🇨🇳',
    name: 'China',
    phone: '86',
    sub: 'CN-86',
  },
  {
    code: 'CX',
    emoji: '🇨🇽',
    name: 'Christmas Island',
    phone: '61',
    sub: 'CX-61',
  },
  {
    code: 'CC',
    emoji: '🇨🇨',
    name: 'Cocos (Keeling) Islands',
    phone: '61',
    sub: 'CC-61',
  },
  {
    code: 'CO',
    emoji: '🇨🇴',
    name: 'Colombia',
    phone: '57',
    sub: 'CO-57',
  },
  {
    code: 'KM',
    emoji: '🇰🇲',
    name: 'Comoros',
    phone: '269',
    sub: 'KM-269',
  },
  {
    code: 'CG',
    emoji: '🇨🇬',
    name: 'Congo',
    phone: '242',
    sub: 'CG-242',
  },
  {
    code: 'CD',
    emoji: '🇨🇩',
    name: 'Congo, The Democratic Republic of the Congo',
    phone: '243',
    sub: 'CD-243',
  },
  {
    code: 'CK',
    emoji: '🇨🇰',
    name: 'Cook Islands',
    phone: '682',
    sub: 'CK-682',
  },
  {
    code: 'CR',
    emoji: '🇨🇷',
    name: 'Costa Rica',
    phone: '506',
    sub: 'CR-506',
  },
  {
    code: 'CI',
    emoji: '🇨🇮',
    name: "Cote d'Ivoire",
    phone: '225',
    sub: 'CI-225',
  },
  {
    code: 'HR',
    emoji: '🇭🇷',
    name: 'Croatia',
    phone: '385',
    sub: 'HR-385',
  },
  {
    code: 'CU',
    emoji: '🇨🇺',
    name: 'Cuba',
    phone: '53',
    sub: 'CU-53',
  },
  {
    code: 'CY',
    emoji: '🇨🇾',
    name: 'Cyprus',
    phone: '357',
    sub: 'CY-357',
  },
  {
    code: 'CZ',
    emoji: '🇨🇿',
    name: 'Czech Republic',
    phone: '420',
    sub: 'CZ-420',
  },
  {
    code: 'DK',
    emoji: '🇩🇰',
    name: 'Denmark',
    phone: '45',
    sub: 'DK-45',
  },
  {
    code: 'DJ',
    emoji: '🇩🇯',
    name: 'Djibouti',
    phone: '253',
    sub: 'DJ-253',
  },
  {
    code: 'DM',
    emoji: '🇩🇲',
    name: 'Dominica',
    phone: '1767',
    sub: 'DM-1767',
  },
  {
    code: 'DO',
    emoji: '🇩🇴',
    name: 'Dominican Republic',
    phone: '1849',
    sub: 'DO-1849',
  },
  {
    code: 'EC',
    emoji: '🇪🇨',
    name: 'Ecuador',
    phone: '593',
    sub: 'EC-593',
  },
  {
    code: 'EG',
    emoji: '🇪🇬',
    name: 'Egypt',
    phone: '20',
    sub: 'EG-20',
  },
  {
    code: 'SV',
    emoji: '🇸🇻',
    name: 'El Salvador',
    phone: '503',
    sub: 'SV-503',
  },
  {
    code: 'GQ',
    emoji: '🇬🇶',
    name: 'Equatorial Guinea',
    phone: '240',
    sub: 'GQ-240',
  },
  {
    code: 'ER',
    emoji: '🇪🇷',
    name: 'Eritrea',
    phone: '291',
    sub: 'ER-291',
  },
  {
    code: 'EE',
    emoji: '🇪🇪',
    name: 'Estonia',
    phone: '372',
    sub: 'EE-372',
  },
  {
    code: 'ET',
    emoji: '🇪🇹',
    name: 'Ethiopia',
    phone: '251',
    sub: 'ET-251',
  },
  {
    code: 'FK',
    emoji: '🇫🇰',
    name: 'Falkland Islands (Malvinas)',
    phone: '500',
    sub: 'FK-500',
  },
  {
    code: 'FO',
    emoji: '🇫🇴',
    name: 'Faroe Islands',
    phone: '298',
    sub: 'FO-298',
  },
  {
    code: 'FJ',
    emoji: '🇫🇯',
    name: 'Fiji',
    phone: '679',
    sub: 'FJ-679',
  },
  {
    code: 'FI',
    emoji: '🇫🇮',
    name: 'Finland',
    phone: '358',
    sub: 'FI-358',
  },
  {
    code: 'FR',
    emoji: '🇫🇷',
    name: 'France',
    phone: '33',
    sub: 'FR-33',
  },
  {
    code: 'GF',
    emoji: '🇬🇫',
    name: 'French Guiana',
    phone: '594',
    sub: 'GF-594',
  },
  {
    code: 'PF',
    emoji: '🇵🇫',
    name: 'French Polynesia',
    phone: '689',
    sub: 'PF-689',
  },
  {
    code: 'TF',
    emoji: '🇹🇫',
    name: 'French Southern Territories',
    phone: '262',
    sub: 'TF-262',
  },
  {
    code: 'GA',
    emoji: '🇬🇦',
    name: 'Gabon',
    phone: '241',
    sub: 'GA-241',
  },
  {
    code: 'GM',
    emoji: '🇬🇲',
    name: 'Gambia',
    phone: '220',
    sub: 'GM-220',
  },
  {
    code: 'GE',
    emoji: '🇬🇪',
    name: 'Georgia',
    phone: '995',
    sub: 'GE-995',
  },
  {
    code: 'DE',
    emoji: '🇩🇪',
    name: 'Germany',
    phone: '49',
    sub: 'DE-49',
  },
  {
    code: 'GH',
    emoji: '🇬🇭',
    name: 'Ghana',
    phone: '233',
    sub: 'GH-233',
  },
  {
    code: 'GI',
    emoji: '🇬🇮',
    name: 'Gibraltar',
    phone: '350',
    sub: 'GI-350',
  },
  {
    code: 'GR',
    emoji: '🇬🇷',
    name: 'Greece',
    phone: '30',
    sub: 'GR-30',
  },
  {
    code: 'GL',
    emoji: '🇬🇱',
    name: 'Greenland',
    phone: '299',
    sub: 'GL-299',
  },
  {
    code: 'GD',
    emoji: '🇬🇩',
    name: 'Grenada',
    phone: '1473',
    sub: 'GD-1473',
  },
  {
    code: 'GP',
    emoji: '🇬🇵',
    name: 'Guadeloupe',
    phone: '590',
    sub: 'GP-590',
  },
  {
    code: 'GU',
    emoji: '🇬🇺',
    name: 'Guam',
    phone: '1671',
    sub: 'GU-1671',
  },
  {
    code: 'GT',
    emoji: '🇬🇹',
    name: 'Guatemala',
    phone: '502',
    sub: 'GT-502',
  },
  {
    code: 'GG',
    emoji: '🇬🇬',
    name: 'Guernsey',
    phone: '44',
    sub: 'GG-44',
  },
  {
    code: 'GN',
    emoji: '🇬🇳',
    name: 'Guinea',
    phone: '224',
    sub: 'GN-224',
  },
  {
    code: 'GW',
    emoji: '🇬🇼',
    name: 'Guinea-Bissau',
    phone: '245',
    sub: 'GW-245',
  },
  {
    code: 'GY',
    emoji: '🇬🇾',
    name: 'Guyana',
    phone: '592',
    sub: 'GY-592',
  },
  {
    code: 'HT',
    emoji: '🇭🇹',
    name: 'Haiti',
    phone: '509',
    sub: 'HT-509',
  },
  {
    code: 'HM',
    emoji: '🇭🇲',
    name: 'Heard Island and Mcdonald Islands',
    phone: '672',
    sub: 'HM-672',
  },
  {
    code: 'VA',
    emoji: '🇻🇦',
    name: 'Holy See (Vatican City State)',
    phone: '379',
    sub: 'VA-379',
  },
  {
    code: 'HN',
    emoji: '🇭🇳',
    name: 'Honduras',
    phone: '504',
    sub: 'HN-504',
  },
  {
    code: 'HK',
    emoji: '🇭🇰',
    name: 'Hong Kong',
    phone: '852',
    sub: 'HK-852',
  },
  {
    code: 'HU',
    emoji: '🇭🇺',
    name: 'Hungary',
    phone: '36',
    sub: 'HU-36',
  },
  {
    code: 'IS',
    emoji: '🇮🇸',
    name: 'Iceland',
    phone: '354',
    sub: 'IS-354',
  },
  {
    code: 'IN',
    emoji: '🇮🇳',
    name: 'India',
    phone: '91',
    sub: 'IN-91',
  },
  {
    code: 'ID',
    emoji: '🇮🇩',
    name: 'Indonesia',
    phone: '62',
    sub: 'ID-62',
  },
  {
    code: 'IR',
    emoji: '🇮🇷',
    name: 'Iran, Islamic Republic of Persian Gulf',
    phone: '98',
    sub: 'IR-98',
  },
  {
    code: 'IQ',
    emoji: '🇮🇶',
    name: 'Iraq',
    phone: '964',
    sub: 'IQ-964',
  },
  {
    code: 'IE',
    emoji: '🇮🇪',
    name: 'Ireland',
    phone: '353',
    sub: 'IE-353',
  },
  {
    code: 'IM',
    emoji: '🇮🇲',
    name: 'Isle of Man',
    phone: '44',
    sub: 'IM-44',
  },
  {
    code: 'IL',
    emoji: '🇮🇱',
    name: 'Israel',
    phone: '972',
    sub: 'IL-972',
  },
  {
    code: 'IT',
    emoji: '🇮🇹',
    name: 'Italy',
    phone: '39',
    sub: 'IT-39',
  },
  {
    code: 'JM',
    emoji: '🇯🇲',
    name: 'Jamaica',
    phone: '1876',
    sub: 'JM-1876',
  },
  {
    code: 'JP',
    emoji: '🇯🇵',
    name: 'Japan',
    phone: '81',
    sub: 'JP-81',
  },
  {
    code: 'JE',
    emoji: '🇯🇪',
    name: 'Jersey',
    phone: '44',
    sub: 'JE-44',
  },
  {
    code: 'JO',
    emoji: '🇯🇴',
    name: 'Jordan',
    phone: '962',
    sub: 'JO-962',
  },
  {
    code: 'KZ',
    emoji: '🇰🇿',
    name: 'Kazakhstan',
    phone: '7',
    sub: 'KZ-7',
  },
  {
    code: 'KE',
    emoji: '🇰🇪',
    name: 'Kenya',
    phone: '254',
    sub: 'KE-254',
  },
  {
    code: 'KI',
    emoji: '🇰🇮',
    name: 'Kiribati',
    phone: '686',
    sub: 'KI-686',
  },
  {
    code: 'KP',
    emoji: '🇰🇵',
    name: "Korea, Democratic People's Republic of Korea",
    phone: '850',
    sub: 'KP-850',
  },
  {
    code: 'KR',
    emoji: '🇰🇷',
    name: 'Korea, Republic of South Korea',
    phone: '82',
    sub: 'KR-82',
  },
  {
    code: 'XK',
    emoji: '🇽🇰',
    name: 'Kosovo',
    phone: '383',
    sub: 'XK-383',
  },
  {
    code: 'KW',
    emoji: '🇰🇼',
    name: 'Kuwait',
    phone: '965',
    sub: 'KW-965',
  },
  {
    code: 'KG',
    emoji: '🇰🇬',
    name: 'Kyrgyzstan',
    phone: '996',
    sub: 'KG-996',
  },
  {
    code: 'LA',
    emoji: '🇱🇦',
    name: 'Laos',
    phone: '856',
    sub: 'LA-856',
  },
  {
    code: 'LV',
    emoji: '🇱🇻',
    name: 'Latvia',
    phone: '371',
    sub: 'LV-371',
  },
  {
    code: 'LB',
    emoji: '🇱🇧',
    name: 'Lebanon',
    phone: '961',
    sub: 'LB-961',
  },
  {
    code: 'LS',
    emoji: '🇱🇸',
    name: 'Lesotho',
    phone: '266',
    sub: 'LS-266',
  },
  {
    code: 'LR',
    emoji: '🇱🇷',
    name: 'Liberia',
    phone: '231',
    sub: 'LR-231',
  },
  {
    code: 'LY',
    emoji: '🇱🇾',
    name: 'Libyan Arab Jamahiriya',
    phone: '218',
    sub: 'LY-218',
  },
  {
    code: 'LI',
    emoji: '🇱🇮',
    name: 'Liechtenstein',
    phone: '423',
    sub: 'LI-423',
  },
  {
    code: 'LT',
    emoji: '🇱🇹',
    name: 'Lithuania',
    phone: '370',
    sub: 'LT-370',
  },
  {
    code: 'LU',
    emoji: '🇱🇺',
    name: 'Luxembourg',
    phone: '352',
    sub: 'LU-352',
  },
  {
    code: 'MO',
    emoji: '🇲🇴',
    name: 'Macao',
    phone: '853',
    sub: 'MO-853',
  },
  {
    code: 'MK',
    emoji: '🇲🇰',
    name: 'Macedonia',
    phone: '389',
    sub: 'MK-389',
  },
  {
    code: 'MG',
    emoji: '🇲🇬',
    name: 'Madagascar',
    phone: '261',
    sub: 'MG-261',
  },
  {
    code: 'MW',
    emoji: '🇲🇼',
    name: 'Malawi',
    phone: '265',
    sub: 'MW-265',
  },
  {
    code: 'MY',
    emoji: '🇲🇾',
    name: 'Malaysia',
    phone: '60',
    sub: 'MY-60',
  },
  {
    code: 'MV',
    emoji: '🇲🇻',
    name: 'Maldives',
    phone: '960',
    sub: 'MV-960',
  },
  {
    code: 'ML',
    emoji: '🇲🇱',
    name: 'Mali',
    phone: '223',
    sub: 'ML-223',
  },
  {
    code: 'MT',
    emoji: '🇲🇹',
    name: 'Malta',
    phone: '356',
    sub: 'MT-356',
  },
  {
    code: 'MH',
    emoji: '🇲🇭',
    name: 'Marshall Islands',
    phone: '692',
    sub: 'MH-692',
  },
  {
    code: 'MQ',
    emoji: '🇲🇶',
    name: 'Martinique',
    phone: '596',
    sub: 'MQ-596',
  },
  {
    code: 'MR',
    emoji: '🇲🇷',
    name: 'Mauritania',
    phone: '222',
    sub: 'MR-222',
  },
  {
    code: 'MU',
    emoji: '🇲🇺',
    name: 'Mauritius',
    phone: '230',
    sub: 'MU-230',
  },
  {
    code: 'YT',
    emoji: '🇾🇹',
    name: 'Mayotte',
    phone: '262',
    sub: 'YT-262',
  },
  {
    code: 'MX',
    emoji: '🇲🇽',
    name: 'Mexico',
    phone: '52',
    sub: 'MX-52',
  },
  {
    code: 'FM',
    emoji: '🇫🇲',
    name: 'Micronesia, Federated States of Micronesia',
    phone: '691',
    sub: 'FM-691',
  },
  {
    code: 'MD',
    emoji: '🇲🇩',
    name: 'Moldova',
    phone: '373',
    sub: 'MD-373',
  },
  {
    code: 'MC',
    emoji: '🇲🇨',
    name: 'Monaco',
    phone: '377',
    sub: 'MC-377',
  },
  {
    code: 'MN',
    emoji: '🇲🇳',
    name: 'Mongolia',
    phone: '976',
    sub: 'MN-976',
  },
  {
    code: 'ME',
    emoji: '🇲🇪',
    name: 'Montenegro',
    phone: '382',
    sub: 'ME-382',
  },
  {
    code: 'MS',
    emoji: '🇲🇸',
    name: 'Montserrat',
    phone: '1664',
    sub: 'MS-1664',
  },
  {
    code: 'MA',
    emoji: '🇲🇦',
    name: 'Morocco',
    phone: '212',
    sub: 'MA-212',
  },
  {
    code: 'MZ',
    emoji: '🇲🇿',
    name: 'Mozambique',
    phone: '258',
    sub: 'MZ-258',
  },
  {
    code: 'MM',
    emoji: '🇲🇲',
    name: 'Myanmar',
    phone: '95',
    sub: 'MM-95',
  },
  {
    code: 'NA',
    emoji: '🇳🇦',
    name: 'Namibia',
    phone: '264',
    sub: 'NA-264',
  },
  {
    code: 'NR',
    emoji: '🇳🇷',
    name: 'Nauru',
    phone: '674',
    sub: 'NR-674',
  },
  {
    code: 'NP',
    emoji: '🇳🇵',
    name: 'Nepal',
    phone: '977',
    sub: 'NP-977',
  },
  {
    code: 'NL',
    emoji: '🇳🇱',
    name: 'Netherlands',
    phone: '31',
    sub: 'NL-31',
  },
  {
    code: 'AN',
    emoji: '',
    name: 'Netherlands Antilles',
    phone: '599',
    sub: 'AN-599',
  },
  {
    code: 'NC',
    emoji: '🇳🇨',
    name: 'New Caledonia',
    phone: '687',
    sub: 'NC-687',
  },
  {
    code: 'NZ',
    emoji: '🇳🇿',
    name: 'New Zealand',
    phone: '64',
    sub: 'NZ-64',
  },
  {
    code: 'NI',
    emoji: '🇳🇮',
    name: 'Nicaragua',
    phone: '505',
    sub: 'NI-505',
  },
  {
    code: 'NE',
    emoji: '🇳🇪',
    name: 'Niger',
    phone: '227',
    sub: 'NE-227',
  },
  {
    code: 'NG',
    emoji: '🇳🇬',
    name: 'Nigeria',
    phone: '234',
    sub: 'NG-234',
  },
  {
    code: 'NU',
    emoji: '🇳🇺',
    name: 'Niue',
    phone: '683',
    sub: 'NU-683',
  },
  {
    code: 'NF',
    emoji: '🇳🇫',
    name: 'Norfolk Island',
    phone: '672',
    sub: 'NF-672',
  },
  {
    code: 'MP',
    emoji: '🇲🇵',
    name: 'Northern Mariana Islands',
    phone: '1670',
    sub: 'MP-1670',
  },
  {
    code: 'NO',
    emoji: '🇳🇴',
    name: 'Norway',
    phone: '47',
    sub: 'NO-47',
  },
  {
    code: 'OM',
    emoji: '🇴🇲',
    name: 'Oman',
    phone: '968',
    sub: 'OM-968',
  },
  {
    code: 'PK',
    emoji: '🇵🇰',
    name: 'Pakistan',
    phone: '92',
    sub: 'PK-92',
  },
  {
    code: 'PW',
    emoji: '🇵🇼',
    name: 'Palau',
    phone: '680',
    sub: 'PW-680',
  },
  {
    code: 'PS',
    emoji: '🇵🇸',
    name: 'Palestinian Territory, Occupied',
    phone: '970',
    sub: 'PS-970',
  },
  {
    code: 'PA',
    emoji: '🇵🇦',
    name: 'Panama',
    phone: '507',
    sub: 'PA-507',
  },
  {
    code: 'PG',
    emoji: '🇵🇬',
    name: 'Papua New Guinea',
    phone: '675',
    sub: 'PG-675',
  },
  {
    code: 'PY',
    emoji: '🇵🇾',
    name: 'Paraguay',
    phone: '595',
    sub: 'PY-595',
  },
  {
    code: 'PE',
    emoji: '🇵🇪',
    name: 'Peru',
    phone: '51',
    sub: 'PE-51',
  },
  {
    code: 'PH',
    emoji: '🇵🇭',
    name: 'Philippines',
    phone: '63',
    sub: 'PH-63',
  },
  {
    code: 'PN',
    emoji: '🇵🇳',
    name: 'Pitcairn',
    phone: '64',
    sub: 'PN-64',
  },
  {
    code: 'PL',
    emoji: '🇵🇱',
    name: 'Poland',
    phone: '48',
    sub: 'PL-48',
  },
  {
    code: 'PT',
    emoji: '🇵🇹',
    name: 'Portugal',
    phone: '351',
    sub: 'PT-351',
  },
  {
    code: 'PR',
    emoji: '🇵🇷',
    name: 'Puerto Rico',
    phone: '1939',
    sub: 'PR-1939',
  },
  {
    code: 'QA',
    emoji: '🇶🇦',
    name: 'Qatar',
    phone: '974',
    sub: 'QA-974',
  },
  {
    code: 'RO',
    emoji: '🇷🇴',
    name: 'Romania',
    phone: '40',
    sub: 'RO-40',
  },
  {
    code: 'RU',
    emoji: '🇷🇺',
    name: 'Russia',
    phone: '7',
    sub: 'RU-7',
  },
  {
    code: 'RW',
    emoji: '🇷🇼',
    name: 'Rwanda',
    phone: '250',
    sub: 'RW-250',
  },
  {
    code: 'RE',
    emoji: '🇷🇪',
    name: 'Reunion',
    phone: '262',
    sub: 'RE-262',
  },
  {
    code: 'BL',
    emoji: '🇧🇱',
    name: 'Saint Barthelemy',
    phone: '590',
    sub: 'BL-590',
  },
  {
    code: 'SH',
    emoji: '🇸🇭',
    name: 'Saint Helena, Ascension and Tristan Da Cunha',
    phone: '290',
    sub: 'SH-290',
  },
  {
    code: 'KN',
    emoji: '🇰🇳',
    name: 'Saint Kitts and Nevis',
    phone: '1869',
    sub: 'KN-1869',
  },
  {
    code: 'LC',
    emoji: '🇱🇨',
    name: 'Saint Lucia',
    phone: '1758',
    sub: 'LC-1758',
  },
  {
    code: 'MF',
    emoji: '🇲🇫',
    name: 'Saint Martin',
    phone: '590',
    sub: 'MF-590',
  },
  {
    code: 'PM',
    emoji: '🇵🇲',
    name: 'Saint Pierre and Miquelon',
    phone: '508',
    sub: 'PM-508',
  },
  {
    code: 'VC',
    emoji: '🇻🇨',
    name: 'Saint Vincent and the Grenadines',
    phone: '1784',
    sub: 'VC-1784',
  },
  {
    code: 'WS',
    emoji: '🇼🇸',
    name: 'Samoa',
    phone: '685',
    sub: 'WS-685',
  },
  {
    code: 'SM',
    emoji: '🇸🇲',
    name: 'San Marino',
    phone: '378',
    sub: 'SM-378',
  },
  {
    code: 'ST',
    emoji: '🇸🇹',
    name: 'Sao Tome and Principe',
    phone: '239',
    sub: 'ST-239',
  },
  {
    code: 'SA',
    emoji: '🇸🇦',
    name: 'Saudi Arabia',
    phone: '966',
    sub: 'SA-966',
  },
  {
    code: 'SN',
    emoji: '🇸🇳',
    name: 'Senegal',
    phone: '221',
    sub: 'SN-221',
  },
  {
    code: 'RS',
    emoji: '🇷🇸',
    name: 'Serbia',
    phone: '381',
    sub: 'RS-381',
  },
  {
    code: 'SC',
    emoji: '🇸🇨',
    name: 'Seychelles',
    phone: '248',
    sub: 'SC-248',
  },
  {
    code: 'SL',
    emoji: '🇸🇱',
    name: 'Sierra Leone',
    phone: '232',
    sub: 'SL-232',
  },
  {
    code: 'SG',
    emoji: '🇸🇬',
    name: 'Singapore',
    phone: '65',
    sub: 'SG-65',
  },
  {
    code: 'SK',
    emoji: '🇸🇰',
    name: 'Slovakia',
    phone: '421',
    sub: 'SK-421',
  },
  {
    code: 'SI',
    emoji: '🇸🇮',
    name: 'Slovenia',
    phone: '386',
    sub: 'SI-386',
  },
  {
    code: 'SB',
    emoji: '🇸🇧',
    name: 'Solomon Islands',
    phone: '677',
    sub: 'SB-677',
  },
  {
    code: 'SO',
    emoji: '🇸🇴',
    name: 'Somalia',
    phone: '252',
    sub: 'SO-252',
  },
  {
    code: 'ZA',
    emoji: '🇿🇦',
    name: 'South Africa',
    phone: '27',
    sub: 'ZA-27',
  },
  {
    code: 'SS',
    emoji: '🇸🇸',
    name: 'South Sudan',
    phone: '211',
    sub: 'SS-211',
  },
  {
    code: 'GS',
    emoji: '🇬🇸',
    name: 'South Georgia and the South Sandwich Islands',
    phone: '500',
    sub: 'GS-500',
  },
  {
    code: 'ES',
    emoji: '🇪🇸',
    name: 'Spain',
    phone: '34',
    sub: 'ES-34',
  },
  {
    code: 'LK',
    emoji: '🇱🇰',
    name: 'Sri Lanka',
    phone: '94',
    sub: 'LK-94',
  },
  {
    code: 'SD',
    emoji: '🇸🇩',
    name: 'Sudan',
    phone: '249',
    sub: 'SD-249',
  },
  {
    code: 'SR',
    emoji: '🇸🇷',
    name: 'Suriname',
    phone: '597',
    sub: 'SR-597',
  },
  {
    code: 'SJ',
    emoji: '🇸🇯',
    name: 'Svalbard and Jan Mayen',
    phone: '47',
    sub: 'SJ-47',
  },
  {
    code: 'SZ',
    emoji: '🇸🇿',
    name: 'Swaziland',
    phone: '268',
    sub: 'SZ-268',
  },
  {
    code: 'SE',
    emoji: '🇸🇪',
    name: 'Sweden',
    phone: '46',
    sub: 'SE-46',
  },
  {
    code: 'CH',
    emoji: '🇨🇭',
    name: 'Switzerland',
    phone: '41',
    sub: 'CH-41',
  },
  {
    code: 'SY',
    emoji: '🇸🇾',
    name: 'Syrian Arab Republic',
    phone: '963',
    sub: 'SY-963',
  },
  {
    code: 'TW',
    emoji: '🇹🇼',
    name: 'Taiwan',
    phone: '886',
    sub: 'TW-886',
  },
  {
    code: 'TJ',
    emoji: '🇹🇯',
    name: 'Tajikistan',
    phone: '992',
    sub: 'TJ-992',
  },
  {
    code: 'TZ',
    emoji: '🇹🇿',
    name: 'Tanzania, United Republic of Tanzania',
    phone: '255',
    sub: 'TZ-255',
  },
  {
    code: 'TH',
    emoji: '🇹🇭',
    name: 'Thailand',
    phone: '66',
    sub: 'TH-66',
  },
  {
    code: 'TL',
    emoji: '🇹🇱',
    name: 'Timor-Leste',
    phone: '670',
    sub: 'TL-670',
  },
  {
    code: 'TG',
    emoji: '🇹🇬',
    name: 'Togo',
    phone: '228',
    sub: 'TG-228',
  },
  {
    code: 'TK',
    emoji: '🇹🇰',
    name: 'Tokelau',
    phone: '690',
    sub: 'TK-690',
  },
  {
    code: 'TO',
    emoji: '🇹🇴',
    name: 'Tonga',
    phone: '676',
    sub: 'TO-676',
  },
  {
    code: 'TT',
    emoji: '🇹🇹',
    name: 'Trinidad and Tobago',
    phone: '1868',
    sub: 'TT-1868',
  },
  {
    code: 'TN',
    emoji: '🇹🇳',
    name: 'Tunisia',
    phone: '216',
    sub: 'TN-216',
  },
  {
    code: 'TR',
    emoji: '🇹🇷',
    name: 'Turkey',
    phone: '90',
    sub: 'TR-90',
  },
  {
    code: 'TM',
    emoji: '🇹🇲',
    name: 'Turkmenistan',
    phone: '993',
    sub: 'TM-993',
  },
  {
    code: 'TC',
    emoji: '🇹🇨',
    name: 'Turks and Caicos Islands',
    phone: '1649',
    sub: 'TC-1649',
  },
  {
    code: 'TV',
    emoji: '🇹🇻',
    name: 'Tuvalu',
    phone: '688',
    sub: 'TV-688',
  },
  {
    code: 'UG',
    emoji: '🇺🇬',
    name: 'Uganda',
    phone: '256',
    sub: 'UG-256',
  },
  {
    code: 'UA',
    emoji: '🇺🇦',
    name: 'Ukraine',
    phone: '380',
    sub: 'UA-380',
  },
  {
    code: 'AE',
    emoji: '🇦🇪',
    name: 'United Arab Emirates',
    phone: '971',
    sub: 'AE-971',
  },
  {
    code: 'GB',
    emoji: '🇬🇧',
    name: 'United Kingdom',
    phone: '44',
    sub: 'GB-44',
  },
  {
    code: 'US',
    emoji: '🇺🇸',
    name: 'United States',
    phone: '1',
    sub: 'US-1',
  },
  {
    code: 'CA',
    emoji: '🇨🇦',
    name: 'Canada',
    phone: '1',
    sub: 'CA-1',
  },
  {
    code: 'UY',
    emoji: '🇺🇾',
    name: 'Uruguay',
    phone: '598',
    sub: 'UY-598',
  },
  {
    code: 'UZ',
    emoji: '🇺🇿',
    name: 'Uzbekistan',
    phone: '998',
    sub: 'UZ-998',
  },
  {
    code: 'VU',
    emoji: '🇻🇺',
    name: 'Vanuatu',
    phone: '678',
    sub: 'VU-678',
  },
  {
    code: 'VE',
    emoji: '🇻🇪',
    name: 'Venezuela, Bolivarian Republic of Venezuela',
    phone: '58',
    sub: 'VE-58',
  },
  {
    code: 'VN',
    emoji: '🇻🇳',
    name: 'Vietnam',
    phone: '84',
    sub: 'VN-84',
  },
  {
    code: 'VG',
    emoji: '🇻🇬',
    name: 'Virgin Islands, British',
    phone: '1284',
    sub: 'VG-1284',
  },
  {
    code: 'VI',
    emoji: '🇻🇮',
    name: 'Virgin Islands, U.S.',
    phone: '1340',
    sub: 'VI-1340',
  },
  {
    code: 'WF',
    emoji: '🇼🇫',
    name: 'Wallis and Futuna',
    phone: '681',
    sub: 'WF-681',
  },
  {
    code: 'YE',
    emoji: '🇾🇪',
    name: 'Yemen',
    phone: '967',
    sub: 'YE-967',
  },
  {
    code: 'ZM',
    emoji: '🇿🇲',
    name: 'Zambia',
    phone: '260',
    sub: 'ZM-260',
  },
  {
    code: 'ZW',
    emoji: '🇿🇼',
    name: 'Zimbabwe',
    phone: '263',
    sub: 'ZW-263',
  },
];

const COUNTRY_CURRENCY_LIST = [
  {
    code: 'AF',
    currency: 'AFN',
    emoji: '🇦🇫',
    name: 'Afghanistan',
  },
  {
    code: 'AL',
    currency: 'ALL',
    emoji: '🇦🇱',
    name: 'Albania',
  },
  {
    code: 'DZ',
    currency: 'DZD',
    emoji: '🇩🇿',
    name: 'Algeria',
  },
  {
    code: 'AS',
    currency: 'USD',
    emoji: '🇦🇸',
    name: 'American Samoa',
  },
  {
    code: 'AD',
    currency: 'EUR',
    emoji: '🇦🇩',
    name: 'Andorra',
  },
  {
    code: 'AO',
    currency: 'AOA',
    emoji: '🇦🇴',
    name: 'Angola',
  },
  {
    code: 'AI',
    currency: 'XCD',
    emoji: '🇦🇮',
    name: 'Anguilla',
  },
  {
    code: 'AQ',
    currency: 'AFN',
    emoji: '🇦🇶',
    name: 'Antarctica',
  },
  {
    code: 'AG',
    currency: 'XCD',
    emoji: '🇦🇬',
    name: 'Antigua and Barbuda',
  },
  {
    code: 'AR',
    currency: 'ARS',
    emoji: '🇦🇷',
    name: 'Argentina',
  },
  {
    code: 'AM',
    currency: 'AMD',
    emoji: '🇦🇲',
    name: 'Armenia',
  },
  {
    code: 'AW',
    currency: 'AWG',
    emoji: '🇦🇼',
    name: 'Aruba',
  },
  {
    code: 'AU',
    currency: 'AUD',
    emoji: '🇦🇺',
    name: 'Australia',
  },
  {
    code: 'AT',
    currency: 'EUR',
    emoji: '🇦🇹',
    name: 'Austria',
  },
  {
    code: 'AZ',
    currency: 'AZN',
    emoji: '🇦🇿',
    name: 'Azerbaijan',
  },
  {
    code: 'BS',
    currency: 'BSD',
    emoji: '🇧🇸',
    name: 'Bahamas',
  },
  {
    code: 'BH',
    currency: 'BHD',
    emoji: '🇧🇭',
    name: 'Bahrain',
  },
  {
    code: 'BD',
    currency: 'BDT',
    emoji: '🇧🇩',
    name: 'Bangladesh',
  },
  {
    code: 'BB',
    currency: 'BBD',
    emoji: '🇧🇧',
    name: 'Barbados',
  },
  {
    code: 'BY',
    currency: 'BYN',
    emoji: '🇧🇾',
    name: 'Belarus',
  },
  {
    code: 'BE',
    currency: 'EUR',
    emoji: '🇧🇪',
    name: 'Belgium',
  },
  {
    code: 'BZ',
    currency: 'BZD',
    emoji: '🇧🇿',
    name: 'Belize',
  },
  {
    code: 'BJ',
    currency: 'XOF',
    emoji: '🇧🇯',
    name: 'Benin',
  },
  {
    code: 'BM',
    currency: 'BMD',
    emoji: '🇧🇲',
    name: 'Bermuda',
  },
  {
    code: 'BT',
    currency: 'BTN',
    emoji: '🇧🇹',
    name: 'Bhutan',
  },
  {
    code: 'BO',
    currency: 'BOB',
    emoji: '🇧🇴',
    name: 'Bolivia, Plurinational State of bolivia',
  },
  {
    code: 'BA',
    currency: 'BAM',
    emoji: '🇧🇦',
    name: 'Bosnia and Herzegovina',
  },
  {
    code: 'BW',
    currency: 'BWP',
    emoji: '🇧🇼',
    name: 'Botswana',
  },
  {
    code: 'BV',
    currency: 'NOK',
    emoji: '🇧🇻',
    name: 'Bouvet Island',
  },
  {
    code: 'BR',
    currency: 'BRL',
    emoji: '🇧🇷',
    name: 'Brazil',
  },
  {
    code: 'IO',
    currency: 'GBP',
    emoji: '🇮🇴',
    name: 'British Indian Ocean Territory',
  },
  {
    code: 'BN',
    currency: 'BND',
    emoji: '🇧🇳',
    name: 'Brunei Darussalam',
  },
  {
    code: 'BG',
    currency: 'BGN',
    emoji: '🇧🇬',
    name: 'Bulgaria',
  },
  {
    code: 'BF',
    currency: 'XOF',
    emoji: '🇧🇫',
    name: 'Burkina Faso',
  },
  {
    code: 'BI',
    currency: 'BIF',
    emoji: '🇧🇮',
    name: 'Burundi',
  },
  {
    code: 'KH',
    currency: 'KHR',
    emoji: '🇰🇭',
    name: 'Cambodia',
  },
  {
    code: 'CM',
    currency: 'XAF',
    emoji: '🇨🇲',
    name: 'Cameroon',
  },
  {
    code: 'CA',
    currency: 'CAD',
    emoji: '🇨🇦',
    name: 'Canada',
  },
  {
    code: 'CV',
    currency: 'CVE',
    emoji: '🇨🇻',
    name: 'Cape Verde',
  },
  {
    code: 'KY',
    currency: 'KYD',
    emoji: '🇰🇾',
    name: 'Cayman Islands',
  },
  {
    code: 'CF',
    currency: 'XAF',
    emoji: '🇨🇫',
    name: 'Central African Republic',
  },
  {
    code: 'TD',
    currency: 'XAF',
    emoji: '🇹🇩',
    name: 'Chad',
  },
  {
    code: 'CL',
    currency: 'CLP',
    emoji: '🇨🇱',
    name: 'Chile',
  },
  {
    code: 'CN',
    currency: 'CNY',
    emoji: '🇨🇳',
    name: 'China',
  },
  {
    code: 'CX',
    currency: 'AUD',
    emoji: '🇨🇽',
    name: 'Christmas Island',
  },
  {
    code: 'CC',
    currency: 'AUD',
    emoji: '🇨🇨',
    name: 'Cocos (Keeling) Islands',
  },
  {
    code: 'CO',
    currency: 'COP',
    emoji: '🇨🇴',
    name: 'Colombia',
  },
  {
    code: 'KM',
    currency: 'KMF',
    emoji: '🇰🇲',
    name: 'Comoros',
  },
  {
    code: 'CG',
    currency: 'XAF',
    emoji: '🇨🇬',
    name: 'Congo',
  },
  {
    code: 'CD',
    currency: 'CDF',
    emoji: '🇨🇩',
    name: 'Congo, The Democratic Republic of the Congo',
  },
  {
    code: 'CK',
    currency: 'NZD',
    emoji: '🇨🇰',
    name: 'Cook Islands',
  },
  {
    code: 'CR',
    currency: 'CRC',
    emoji: '🇨🇷',
    name: 'Costa Rica',
  },
  {
    code: 'CI',
    currency: 'CFA',
    emoji: '🇨🇮',
    name: "Cote d'Ivoire",
  },
  {
    code: 'HR',
    currency: 'EUR',
    emoji: '🇭🇷',
    name: 'Croatia',
  },
  {
    code: 'CU',
    currency: 'CUC',
    emoji: '🇨🇺',
    name: 'Cuba',
  },
  {
    code: 'CY',
    currency: 'EUR',
    emoji: '🇨🇾',
    name: 'Cyprus',
  },
  {
    code: 'CZ',
    currency: 'CZK',
    emoji: '🇨🇿',
    name: 'Czech Republic',
  },
  {
    code: 'DK',
    currency: 'DKK',
    emoji: '🇩🇰',
    name: 'Denmark',
  },
  {
    code: 'DJ',
    currency: 'DJF',
    emoji: '🇩🇯',
    name: 'Djibouti',
  },
  {
    code: 'DM',
    currency: 'XCD',
    emoji: '🇩🇲',
    name: 'Dominica',
  },
  {
    code: 'DO',
    currency: 'DOP',
    emoji: '🇩🇴',
    name: 'Dominican Republic',
  },
  {
    code: 'EC',
    currency: 'USD',
    emoji: '🇪🇨',
    name: 'Ecuador',
  },
  {
    code: 'EG',
    currency: 'EGP',
    emoji: '🇪🇬',
    name: 'Egypt',
  },
  {
    code: 'SV',
    currency: 'USD',
    emoji: '🇸🇻',
    name: 'El Salvador',
  },
  {
    code: 'GQ',
    currency: 'XAF',
    emoji: '🇬🇶',
    name: 'Equatorial Guinea',
  },
  {
    code: 'ER',
    currency: 'ERN',
    emoji: '🇪🇷',
    name: 'Eritrea',
  },
  {
    code: 'EE',
    currency: 'EUR',
    emoji: '🇪🇪',
    name: 'Estonia',
  },
  {
    code: 'ET',
    currency: 'ETB',
    emoji: '🇪🇹',
    name: 'Ethiopia',
  },
  {
    code: 'FK',
    currency: 'FKP',
    emoji: '🇫🇰',
    name: 'Falkland Islands (Malvinas)',
  },
  {
    code: 'FO',
    currency: 'DKK',
    emoji: '🇫🇴',
    name: 'Faroe Islands',
  },
  {
    code: 'FJ',
    currency: 'FJD',
    emoji: '🇫🇯',
    name: 'Fiji',
  },
  {
    code: 'FI',
    currency: 'EUR',
    emoji: '🇫🇮',
    name: 'Finland',
  },
  {
    code: 'FR',
    currency: 'EUR',
    emoji: '🇫🇷',
    name: 'France',
  },
  {
    code: 'GF',
    currency: 'EUR',
    emoji: '🇬🇫',
    name: 'French Guiana',
  },
  {
    code: 'PF',
    currency: 'XPF',
    emoji: '🇵🇫',
    name: 'French Polynesia',
  },
  {
    code: 'TF',
    currency: 'EUR',
    emoji: '🇹🇫',
    name: 'French Southern Territories',
  },
  {
    code: 'GA',
    currency: 'XAF',
    emoji: '🇬🇦',
    name: 'Gabon',
  },
  {
    code: 'GM',
    currency: 'GMD',
    emoji: '🇬🇲',
    name: 'Gambia',
  },
  {
    code: 'GE',
    currency: 'GEL',
    emoji: '🇬🇪',
    name: 'Georgia',
  },
  {
    code: 'DE',
    currency: 'EUR',
    emoji: '🇩🇪',
    name: 'Germany',
  },
  {
    code: 'GH',
    currency: 'GHS',
    emoji: '🇬🇭',
    name: 'Ghana',
  },
  {
    code: 'GI',
    currency: 'GIP',
    emoji: '🇬🇮',
    name: 'Gibraltar',
  },
  {
    code: 'GR',
    currency: 'EUR',
    emoji: '🇬🇷',
    name: 'Greece',
  },
  {
    code: 'GL',
    currency: 'DKK',
    emoji: '🇬🇱',
    name: 'Greenland',
  },
  {
    code: 'GD',
    currency: 'XCD',
    emoji: '🇬🇩',
    name: 'Grenada',
  },
  {
    code: 'GP',
    currency: 'EUR',
    emoji: '🇬🇵',
    name: 'Guadeloupe',
  },
  {
    code: 'GU',
    currency: 'USD',
    emoji: '🇬🇺',
    name: 'Guam',
  },
  {
    code: 'GT',
    currency: 'GTQ',
    emoji: '🇬🇹',
    name: 'Guatemala',
  },
  {
    code: 'GG',
    currency: 'GGP',
    emoji: '🇬🇬',
    name: 'Guernsey',
  },
  {
    code: 'GN',
    currency: 'GNF',
    emoji: '🇬🇳',
    name: 'Guinea',
  },
  {
    code: 'GW',
    currency: 'XOF',
    emoji: '🇬🇼',
    name: 'Guinea-Bissau',
  },
  {
    code: 'GY',
    currency: 'GYD',
    emoji: '🇬🇾',
    name: 'Guyana',
  },
  {
    code: 'HT',
    currency: 'HTG',
    emoji: '🇭🇹',
    name: 'Haiti',
  },
  {
    code: 'HM',
    currency: 'AUD',
    emoji: '🇭🇲',
    name: 'Heard Island and Mcdonald Islands',
  },
  {
    code: 'VA',
    currency: 'EUR',
    emoji: '🇻🇦',
    name: 'Holy See (Vatican City State)',
  },
  {
    code: 'HN',
    currency: 'HNL',
    emoji: '🇭🇳',
    name: 'Honduras',
  },
  {
    code: 'HK',
    currency: 'HKD',
    emoji: '🇭🇰',
    name: 'Hong Kong',
  },
  {
    code: 'HU',
    currency: 'HUF',
    emoji: '🇭🇺',
    name: 'Hungary',
  },
  {
    code: 'IS',
    currency: 'ISK',
    emoji: '🇮🇸',
    name: 'Iceland',
  },
  {
    code: 'IN',
    currency: 'INR',
    emoji: '🇮🇳',
    name: 'India',
  },
  {
    code: 'ID',
    currency: 'IDR',
    emoji: '🇮🇩',
    name: 'Indonesia',
  },
  {
    code: 'IR',
    currency: 'IRR',
    emoji: '🇮🇷',
    name: 'Iran, Islamic Republic of Persian Gulf',
  },
  {
    code: 'IQ',
    currency: 'IQD',
    emoji: '🇮🇶',
    name: 'Iraq',
  },
  {
    code: 'IE',
    currency: 'EUR',
    emoji: '🇮🇪',
    name: 'Ireland',
  },
  {
    code: 'IM',
    currency: 'IMP',
    emoji: '🇮🇲',
    name: 'Isle of Man',
  },
  {
    code: 'IL',
    currency: 'ILS',
    emoji: '🇮🇱',
    name: 'Israel',
  },
  {
    code: 'IT',
    currency: 'EUR',
    emoji: '🇮🇹',
    name: 'Italy',
  },
  {
    code: 'JM',
    currency: 'JMD',
    emoji: '🇯🇲',
    name: 'Jamaica',
  },
  {
    code: 'JP',
    currency: 'JPY',
    emoji: '🇯🇵',
    name: 'Japan',
  },
  {
    code: 'JE',
    currency: 'JEP',
    emoji: '🇯🇪',
    name: 'Jersey',
  },
  {
    code: 'JO',
    currency: 'JOD',
    emoji: '🇯🇴',
    name: 'Jordan',
  },
  {
    code: 'KZ',
    currency: 'KZT',
    emoji: '🇰🇿',
    name: 'Kazakhstan',
  },
  {
    code: 'KE',
    currency: 'KES',
    emoji: '🇰🇪',
    name: 'Kenya',
  },
  {
    code: 'KI',
    currency: 'AUD',
    emoji: '🇰🇮',
    name: 'Kiribati',
  },
  {
    code: 'KP',
    currency: 'KPW',
    emoji: '🇰🇵',
    name: "Korea, Democratic People's Republic of Korea",
  },
  {
    code: 'KR',
    currency: 'KRW',
    emoji: '🇰🇷',
    name: 'Korea, Republic of South Korea',
  },
  {
    code: 'XK',
    currency: 'EUR',
    emoji: '🇽🇰',
    name: 'Kosovo',
  },
  {
    code: 'KW',
    currency: 'KWD',
    emoji: '🇰🇼',
    name: 'Kuwait',
  },
  {
    code: 'KG',
    currency: 'KGS',
    emoji: '🇰🇬',
    name: 'Kyrgyzstan',
  },
  {
    code: 'LA',
    currency: 'LAK',
    emoji: '🇱🇦',
    name: 'Laos',
  },
  {
    code: 'LV',
    currency: 'EUR',
    emoji: '🇱🇻',
    name: 'Latvia',
  },
  {
    code: 'LB',
    currency: 'LBP',
    emoji: '🇱🇧',
    name: 'Lebanon',
  },
  {
    code: 'LS',
    currency: 'LSL',
    emoji: '🇱🇸',
    name: 'Lesotho',
  },
  {
    code: 'LR',
    currency: 'LRD',
    emoji: '🇱🇷',
    name: 'Liberia',
  },
  {
    code: 'LY',
    currency: 'LYD',
    emoji: '🇱🇾',
    name: 'Libyan Arab Jamahiriya',
  },
  {
    code: 'LI',
    currency: 'CHF',
    emoji: '🇱🇮',
    name: 'Liechtenstein',
  },
  {
    code: 'LT',
    currency: 'LTL',
    emoji: '🇱🇹',
    name: 'Lithuania',
  },
  {
    code: 'LU',
    currency: 'EUR',
    emoji: '🇱🇺',
    name: 'Luxembourg',
  },
  {
    code: 'MO',
    currency: 'MOP',
    emoji: '🇲🇴',
    name: 'Macao',
  },
  {
    code: 'MK',
    currency: 'MKD',
    emoji: '🇲🇰',
    name: 'Macedonia',
  },
  {
    code: 'MG',
    currency: 'MGA',
    emoji: '🇲🇬',
    name: 'Madagascar',
  },
  {
    code: 'MW',
    currency: 'MWK',
    emoji: '🇲🇼',
    name: 'Malawi',
  },
  {
    code: 'MY',
    currency: 'MYR',
    emoji: '🇲🇾',
    name: 'Malaysia',
  },
  {
    code: 'MV',
    currency: 'MVR',
    emoji: '🇲🇻',
    name: 'Maldives',
  },
  {
    code: 'ML',
    currency: 'XOF',
    emoji: '🇲🇱',
    name: 'Mali',
  },
  {
    code: 'MT',
    currency: 'EUR',
    emoji: '🇲🇹',
    name: 'Malta',
  },
  {
    code: 'MH',
    currency: 'USD',
    emoji: '🇲🇭',
    name: 'Marshall Islands',
  },
  {
    code: 'MQ',
    currency: 'EUR',
    emoji: '🇲🇶',
    name: 'Martinique',
  },
  {
    code: 'MR',
    currency: 'MRU',
    emoji: '🇲🇷',
    name: 'Mauritania',
  },
  {
    code: 'MU',
    currency: 'MUR',
    emoji: '🇲🇺',
    name: 'Mauritius',
  },
  {
    code: 'YT',
    currency: 'EUR',
    emoji: '🇾🇹',
    name: 'Mayotte',
  },
  {
    code: 'MX',
    currency: 'MXN',
    emoji: '🇲🇽',
    name: 'Mexico',
  },
  {
    code: 'FM',
    currency: 'USD',
    emoji: '🇫🇲',
    name: 'Micronesia, Federated States of Micronesia',
  },
  {
    code: 'MD',
    currency: 'MDL',
    emoji: '🇲🇩',
    name: 'Moldova',
  },
  {
    code: 'MC',
    currency: 'EUR',
    emoji: '🇲🇨',
    name: 'Monaco',
  },
  {
    code: 'MN',
    currency: 'MNT',
    emoji: '🇲🇳',
    name: 'Mongolia',
  },
  {
    code: 'ME',
    currency: 'EUR',
    emoji: '🇲🇪',
    name: 'Montenegro',
  },
  {
    code: 'MS',
    currency: 'XCD',
    emoji: '🇲🇸',
    name: 'Montserrat',
  },
  {
    code: 'MA',
    currency: 'MAD',
    emoji: '🇲🇦',
    name: 'Morocco',
  },
  {
    code: 'MZ',
    currency: 'MZN',
    emoji: '🇲🇿',
    name: 'Mozambique',
  },
  {
    code: 'MM',
    currency: 'MMK',
    emoji: '🇲🇲',
    name: 'Myanmar',
  },
  {
    code: 'NA',
    currency: 'NAD',
    emoji: '🇳🇦',
    name: 'Namibia',
  },
  {
    code: 'NR',
    currency: 'AUD',
    emoji: '🇳🇷',
    name: 'Nauru',
  },
  {
    code: 'NP',
    currency: 'NPR',
    emoji: '🇳🇵',
    name: 'Nepal',
  },
  {
    code: 'NL',
    currency: 'EUR',
    emoji: '🇳🇱',
    name: 'Netherlands',
  },
  {
    code: 'AN',
    currency: 'ANG',
    emoji: '',
    name: 'Netherlands Antilles',
  },
  {
    code: 'NC',
    currency: 'XPF',
    emoji: '🇳🇨',
    name: 'New Caledonia',
  },
  {
    code: 'NZ',
    currency: 'NZD',
    emoji: '🇳🇿',
    name: 'New Zealand',
  },
  {
    code: 'NI',
    currency: 'NIO',
    emoji: '🇳🇮',
    name: 'Nicaragua',
  },
  {
    code: 'NE',
    currency: 'XOF',
    emoji: '🇳🇪',
    name: 'Niger',
  },
  {
    code: 'NG',
    currency: 'NGN',
    emoji: '🇳🇬',
    name: 'Nigeria',
  },
  {
    code: 'NU',
    currency: 'NZD',
    emoji: '🇳🇺',
    name: 'Niue',
  },
  {
    code: 'NF',
    currency: 'AUD',
    emoji: '🇳🇫',
    name: 'Norfolk Island',
  },
  {
    code: 'MP',
    currency: 'USD',
    emoji: '🇲🇵',
    name: 'Northern Mariana Islands',
  },
  {
    code: 'NO',
    currency: 'NOK',
    emoji: '🇳🇴',
    name: 'Norway',
  },
  {
    code: 'OM',
    currency: 'OMR',
    emoji: '🇴🇲',
    name: 'Oman',
  },
  {
    code: 'PK',
    currency: 'PKR',
    emoji: '🇵🇰',
    name: 'Pakistan',
  },
  {
    code: 'PW',
    currency: 'USD',
    emoji: '🇵🇼',
    name: 'Palau',
  },
  {
    code: 'PS',
    currency: 'ILS',
    emoji: '🇵🇸',
    name: 'Palestinian Territory, Occupied',
  },
  {
    code: 'PA',
    currency: 'PAB',
    emoji: '🇵🇦',
    name: 'Panama',
  },
  {
    code: 'PG',
    currency: 'PGK',
    emoji: '🇵🇬',
    name: 'Papua New Guinea',
  },
  {
    code: 'PY',
    currency: 'PYG',
    emoji: '🇵🇾',
    name: 'Paraguay',
  },
  {
    code: 'PE',
    currency: 'PEN',
    emoji: '🇵🇪',
    name: 'Peru',
  },
  {
    code: 'PH',
    currency: 'PHP',
    emoji: '🇵🇭',
    name: 'Philippines',
  },
  {
    code: 'PN',
    currency: 'NZD',
    emoji: '🇵🇳',
    name: 'Pitcairn',
  },
  {
    code: 'PL',
    currency: 'PLN',
    emoji: '🇵🇱',
    name: 'Poland',
  },
  {
    code: 'PT',
    currency: 'EUR',
    emoji: '🇵🇹',
    name: 'Portugal',
  },
  {
    code: 'PR',
    currency: 'USD',
    emoji: '🇵🇷',
    name: 'Puerto Rico',
  },
  {
    code: 'QA',
    currency: 'QAR',
    emoji: '🇶🇦',
    name: 'Qatar',
  },
  {
    code: 'RO',
    currency: 'RON',
    emoji: '🇷🇴',
    name: 'Romania',
  },
  {
    code: 'RU',
    currency: 'RUB',
    emoji: '🇷🇺',
    name: 'Russia',
  },
  {
    code: 'RW',
    currency: 'RWF',
    emoji: '🇷🇼',
    name: 'Rwanda',
  },
  {
    code: 'RE',
    currency: 'EUR',
    emoji: '🇷🇪',
    name: 'Reunion',
  },
  {
    code: 'BL',
    currency: 'NAD',
    emoji: '🇧🇱',
    name: 'Saint Barthelemy',
  },
  {
    code: 'SH',
    currency: 'SHP',
    emoji: '🇸🇭',
    name: 'Saint Helena, Ascension and Tristan Da Cunha',
  },
  {
    code: 'KN',
    currency: 'ECD',
    emoji: '🇰🇳',
    name: 'Saint Kitts and Nevis',
  },
  {
    code: 'LC',
    currency: 'XCD',
    emoji: '🇱🇨',
    name: 'Saint Lucia',
  },
  {
    code: 'MF',
    currency: 'EUR',
    emoji: '🇲🇫',
    name: 'Saint Martin',
  },
  {
    code: 'PM',
    currency: 'EUR',
    emoji: '🇵🇲',
    name: 'Saint Pierre and Miquelon',
  },
  {
    code: 'VC',
    currency: 'XCD',
    emoji: '🇻🇨',
    name: 'Saint Vincent and the Grenadines',
  },
  {
    code: 'WS',
    currency: 'WST',
    emoji: '🇼🇸',
    name: 'Samoa',
  },
  {
    code: 'SM',
    currency: 'EUR',
    emoji: '🇸🇲',
    name: 'San Marino',
  },
  {
    code: 'ST',
    currency: 'NAD',
    emoji: '🇸🇹',
    name: 'Sao Tome and Principe',
  },
  {
    code: 'SA',
    currency: 'SAR',
    emoji: '🇸🇦',
    name: 'Saudi Arabia',
  },
  {
    code: 'SN',
    currency: 'XOF',
    emoji: '🇸🇳',
    name: 'Senegal',
  },
  {
    code: 'RS',
    currency: 'RSD',
    emoji: '🇷🇸',
    name: 'Serbia',
  },
  {
    code: 'SC',
    currency: 'SCR',
    emoji: '🇸🇨',
    name: 'Seychelles',
  },
  {
    code: 'SL',
    currency: 'SLE',
    emoji: '🇸🇱',
    name: 'Sierra Leone',
  },
  {
    code: 'SG',
    currency: 'SGD',
    emoji: '🇸🇬',
    name: 'Singapore',
  },
  {
    code: 'SK',
    currency: 'EUR',
    emoji: '🇸🇰',
    name: 'Slovakia',
  },
  {
    code: 'SI',
    currency: 'EUR',
    emoji: '🇸🇮',
    name: 'Slovenia',
  },
  {
    code: 'SB',
    currency: 'SBD',
    emoji: '🇸🇧',
    name: 'Solomon Islands',
  },
  {
    code: 'SO',
    currency: 'SOS',
    emoji: '🇸🇴',
    name: 'Somalia',
  },
  {
    code: 'ZA',
    currency: 'ZAR',
    emoji: '🇿🇦',
    name: 'South Africa',
  },
  {
    code: 'SS',
    currency: 'SSP',
    emoji: '🇸🇸',
    name: 'South Sudan',
  },
  {
    code: 'GS',
    currency: 'GBP',
    emoji: '🇬🇸',
    name: 'South Georgia and the South Sandwich Islands',
  },
  {
    code: 'ES',
    currency: 'EUR',
    emoji: '🇪🇸',
    name: 'Spain',
  },
  {
    code: 'LK',
    currency: 'LKR',
    emoji: '🇱🇰',
    name: 'Sri Lanka',
  },
  {
    code: 'SD',
    currency: 'SDG',
    emoji: '🇸🇩',
    name: 'Sudan',
  },
  {
    code: 'SR',
    currency: 'SRD',
    emoji: '🇸🇷',
    name: 'Suriname',
  },
  {
    code: 'SJ',
    currency: 'NOK',
    emoji: '🇸🇯',
    name: 'Svalbard and Jan Mayen',
  },
  {
    code: 'SZ',
    currency: 'SZL',
    emoji: '🇸🇿',
    name: 'Swaziland',
  },
  {
    code: 'SE',
    currency: 'SEK',
    emoji: '🇸🇪',
    name: 'Sweden',
  },
  {
    code: 'CH',
    currency: 'CHF',
    emoji: '🇨🇭',
    name: 'Switzerland',
  },
  {
    code: 'SY',
    currency: 'SYP',
    emoji: '🇸🇾',
    name: 'Syrian Arab Republic',
  },
  {
    code: 'TW',
    currency: 'TWD',
    emoji: '🇹🇼',
    name: 'Taiwan',
  },
  {
    code: 'TJ',
    currency: 'TJS',
    emoji: '🇹🇯',
    name: 'Tajikistan',
  },
  {
    code: 'TZ',
    currency: 'TZS',
    emoji: '🇹🇿',
    name: 'Tanzania, United Republic of Tanzania',
  },
  {
    code: 'TH',
    currency: 'THB',
    emoji: '🇹🇭',
    name: 'Thailand',
  },
  {
    code: 'TL',
    currency: 'USD',
    emoji: '🇹🇱',
    name: 'Timor-Leste',
  },
  {
    code: 'TG',
    currency: 'XOF',
    emoji: '🇹🇬',
    name: 'Togo',
  },
  {
    code: 'TK',
    currency: 'NZD',
    emoji: '🇹🇰',
    name: 'Tokelau',
  },
  {
    code: 'TO',
    currency: 'TOP',
    emoji: '🇹🇴',
    name: 'Tonga',
  },
  {
    code: 'TT',
    currency: 'TTD',
    emoji: '🇹🇹',
    name: 'Trinidad and Tobago',
  },
  {
    code: 'TN',
    currency: 'TND',
    emoji: '🇹🇳',
    name: 'Tunisia',
  },
  {
    code: 'TR',
    currency: 'TRY',
    emoji: '🇹🇷',
    name: 'Turkey',
  },
  {
    code: 'TM',
    currency: 'TMT',
    emoji: '🇹🇲',
    name: 'Turkmenistan',
  },
  {
    code: 'TC',
    currency: 'USD',
    emoji: '🇹🇨',
    name: 'Turks and Caicos Islands',
  },
  {
    code: 'TV',
    currency: 'AUD',
    emoji: '🇹🇻',
    name: 'Tuvalu',
  },
  {
    code: 'UG',
    currency: 'UGX',
    emoji: '🇺🇬',
    name: 'Uganda',
  },
  {
    code: 'UA',
    currency: 'UAH',
    emoji: '🇺🇦',
    name: 'Ukraine',
  },
  {
    code: 'AE',
    currency: 'AED',
    emoji: '🇦🇪',
    name: 'United Arab Emirates',
  },
  {
    code: 'GB',
    currency: 'GBP',
    emoji: '🇬🇧',
    name: 'United Kingdom',
  },
  {
    code: 'US',
    currency: 'USD',
    emoji: '🇺🇸',
    name: 'United States',
  },
  {
    code: 'UY',
    currency: 'UYU',
    emoji: '🇺🇾',
    name: 'Uruguay',
  },
  {
    code: 'UZ',
    currency: 'UZS',
    emoji: '🇺🇿',
    name: 'Uzbekistan',
  },
  {
    code: 'VU',
    currency: 'VUV',
    emoji: '🇻🇺',
    name: 'Vanuatu',
  },
  {
    code: 'VE',
    currency: 'VES',
    emoji: '🇻🇪',
    name: 'Venezuela, Bolivarian Republic of Venezuela',
  },
  {
    code: 'VN',
    currency: 'VND',
    emoji: '🇻🇳',
    name: 'Vietnam',
  },
  {
    code: 'VG',
    currency: 'USD',
    emoji: '🇻🇬',
    name: 'Virgin Islands, British',
  },
  {
    code: 'VI',
    currency: 'USD',
    emoji: '🇻🇮',
    name: 'Virgin Islands, U.S.',
  },
  {
    code: 'WF',
    currency: 'XPF',
    emoji: '🇼🇫',
    name: 'Wallis and Futuna',
  },
  {
    code: 'YE',
    currency: 'YER',
    emoji: '🇾🇪',
    name: 'Yemen',
  },
  {
    code: 'ZM',
    currency: 'ZMW',
    emoji: '🇿🇲',
    name: 'Zambia',
  },
  {
    code: 'ZW',
    currency: 'ZWL',
    emoji: '🇿🇼',
    name: 'Zimbabwe',
  },
];

export { COUNTRY_CODE_LIST };
